SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    o.ORDER_DATE,
    o.ORDER_VALUE,
    p.PRODUCT_NAME,
    COUNT(o.ORDER_ID) AS ORDER_COUNT,
    SUM(o.ORDER_VALUE) AS REVENUE
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.ORDER_DATE BETWEEN @StartDate AND @EndDate
  AND c.REGION IN (@Region)
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION, o.ORDER_DATE, o.ORDER_VALUE, p.PRODUCT_NAME
